server:
  port: 8001
spring:
  application:
    name: room-booking-gateway
  profiles:
    active: enc
  cloud:
    gateway:
      routes:
        - id: room-booking-test
          uri: lb://room-booking-test
          predicates:
            - Path=/test
            - Query=admin
        - id: room-booking-oauth2
          uri: lb://room-booking-oauth2
          predicates:
            - Path=/*/login